### ISSUE TITLE
win32 crashes USB stack

### ISSUE THREAD

**Issue by bjc** [bjc/ArduinoCore-GD32#6]
Enumeration doesn't finish when plugging device into win32 host.

**Comment by obra** [comment]
Note that everything works fine with the test sketch in extra/gd32usb-test.

What I'm seeing is enumeration and usually the ability to send maybe a packet or two and then a device crash or re-enumeration loop in Kaleidoscope. If I disable the AbsoluteMouse (Graphics tablet) driver in Kaleidoscope, everything seems to work great in Windows.

This is a "good" enumeration on macos:

![image](https://user-images.githubusercontent.com/45416/146450057-fa8ff4ff-6cf8-4311-83b5-b30da95f3093.png)

This is a "bad" enumeration on Windows:

![image](https://user-images.githubusercontent.com/45416/146450098-ddfdc21f-feff-409f-9147-d56587bdd6fd.png)
![image](https://user-images.githubusercontent.com/45416/146450111-24a50cf2-fa0f-4cf6-a08d-b79cbc759ed3.png)

I have not yet managed to build a repro case without Kaleidoscope in the loop, but am happy to dig into that now.

**Comment by obra** [comment]
Ok. I *believe* that this crashes on Win32. And it works correctly on macOS
[gd32usb-test.ino.txt](https://github.com/bjc/ArduinoCore-GD32/files/7730721/gd32usb-test.ino.txt)
.

**Comment by bjc** [comment]
Issue was with padding on gd32, and it's been fixed in KeyboardioHID.
