### ISSUE TITLE
Using a total of 6 endpoints seems to cause an assert failure due to buffer sizing calculation

### ISSUE THREAD

**Issue by obra** [bjc/ArduinoCore-GD32#7]
I've finally figured out why enabling both Serial and HID Mouse support has been locking up Kaleidoscope.

We're failing 

```                // Don’t overflow the hardware buffer table.
                assert((buf_offset + ep_desc.wMaxPacketSize) <= 512);
```

It looks like you're automatically assuming that every endpoint should have a 64 byte buffer.

This is how the Model 100 *wants* to enumerate:

![image](https://user-images.githubusercontent.com/45416/154165989-027fcf75-a656-42d7-8cf6-1db0cbe54c86.png)

I can reproduce the failure I'm seeing with the attached sketch that simulates how Kaleidoscope inits HID.
[gd32usb-test.txt](https://github.com/bjc/ArduinoCore-GD32/files/8075379/gd32usb-test.txt)

As a debugging tactic, I modified line 325 of USBCore.cpp to read:

`                    .wMaxPacketSize = USB_EP_SIZE/2,`

This is obviously *not* correct, but it does result in basic functionality working for me.

Given that the chip supports up to 8 endpoints with its 512b of USB buffer RAM, there ought to be a way to make this go, right?

**Comment by bjc** [comment]
https://github.com/bjc/ArduinoCore-GD32/commit/298e5fb99a517f4aca5b35ab0f8f0d09054a19b9 now allows specifying the buffer size on the USB peripheral, so you can exceed 5 custom endpoints provided they have small enough wMaxPacketLengths.
